"""지도점검 종합 체크리스트 템플릿 — '지도점검_종합체크리스트.docx'에서 추출 (152항목)."""

AUDIT_TEMPLATE = [
    {"section": "기관 기본 운영", "sub": "기관 기본 서류", "title": "장기요양기관 지정서", "order": 0},
    {"section": "기관 기본 운영", "sub": "기관 기본 서류", "title": "사업자등록증", "order": 1},
    {"section": "기관 기본 운영", "sub": "기관 기본 서류", "title": "시설 운영규정", "order": 2},
    {"section": "기관 기본 운영", "sub": "기관 기본 서류", "title": "조직도", "order": 3},
    {"section": "기관 기본 운영", "sub": "기관 기본 서류", "title": "기관 현황", "order": 4},
    {"section": "기관 기본 운영", "sub": "기관 기본 서류", "title": "운영위원회 관련 서류", "order": 5},
    {"section": "기관 기본 운영", "sub": "기관 기본 서류", "title": "기관 보험 가입 서류", "order": 6},
    {"section": "인사·종사자 관리", "sub": "인사 서류", "title": "직원 명부", "order": 7},
    {"section": "인사·종사자 관리", "sub": "인사 서류", "title": "자격증 및 면허증 사본", "order": 8},
    {"section": "인사·종사자 관리", "sub": "인사 서류", "title": "근로계약서", "order": 9},
    {"section": "인사·종사자 관리", "sub": "인사 서류", "title": "4대 보험 가입 서류", "order": 10},
    {"section": "인사·종사자 관리", "sub": "인사 서류", "title": "건강검진 결과", "order": 11},
    {"section": "인사·종사자 관리", "sub": "인사 서류", "title": "결핵검진 결과", "order": 12},
    {"section": "인사·종사자 관리", "sub": "인사 서류", "title": "보수교육 이수증", "order": 13},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "노인인권교육", "order": 14},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "노인학대 예방교육", "order": 15},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "감염관리 교육", "order": 16},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "응급처치 교육", "order": 17},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "개인정보보호 교육", "order": 18},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "성희롱 예방교육", "order": 19},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "장애인 인식개선교육", "order": 20},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "산업안전보건교육(해당 시)", "order": 21},
    {"section": "인사·종사자 관리", "sub": "법정의무교육", "title": "기타 법정교육", "order": 22},
    {"section": "근무관리", "sub": None, "title": "근무표", "order": 23},
    {"section": "근무관리", "sub": None, "title": "출퇴근기록부", "order": 24},
    {"section": "근무관리", "sub": None, "title": "연장근무 기록", "order": 25},
    {"section": "근무관리", "sub": None, "title": "야간근무 기록", "order": 26},
    {"section": "근무관리", "sub": None, "title": "휴일근무 기록", "order": 27},
    {"section": "근무관리", "sub": None, "title": "연차관리", "order": 28},
    {"section": "근무관리", "sub": None, "title": "인력배치기준 충족 여부", "order": 29},
    {"section": "근무관리", "sub": None, "title": "가산 관련 근무기록", "order": 30},
    {"section": "입소관리", "sub": None, "title": "입소계약서", "order": 31},
    {"section": "입소관리", "sub": None, "title": "장기요양인정서", "order": 32},
    {"section": "입소관리", "sub": None, "title": "표준장기요양이용계획서", "order": 33},
    {"section": "입소관리", "sub": None, "title": "시설급여 계약서", "order": 34},
    {"section": "입소관리", "sub": None, "title": "개인정보 수집·이용 동의서", "order": 35},
    {"section": "입소관리", "sub": None, "title": "보호자 동의서", "order": 36},
    {"section": "입소관리", "sub": None, "title": "입소 초기 사정기록", "order": 37},
    {"section": "입소관리", "sub": None, "title": "입·퇴소 관리대장", "order": 38},
    {"section": "입소관리", "sub": None, "title": "외출·외박 관리대장", "order": 39},
    {"section": "급여제공 관리", "sub": None, "title": "급여제공계획서", "order": 40},
    {"section": "급여제공 관리", "sub": None, "title": "급여제공기록지", "order": 41},
    {"section": "급여제공 관리", "sub": None, "title": "요양기록지", "order": 42},
    {"section": "급여제공 관리", "sub": None, "title": "간호기록지", "order": 43},
    {"section": "급여제공 관리", "sub": None, "title": "재활기록지", "order": 44},
    {"section": "급여제공 관리", "sub": None, "title": "식사기록", "order": 45},
    {"section": "급여제공 관리", "sub": None, "title": "배변기록", "order": 46},
    {"section": "급여제공 관리", "sub": None, "title": "목욕기록", "order": 47},
    {"section": "급여제공 관리", "sub": None, "title": "체위변경 기록", "order": 48},
    {"section": "급여제공 관리", "sub": None, "title": "서비스 제공시간 기록", "order": 49},
    {"section": "급여제공 관리", "sub": None, "title": "보호자 통보 기록", "order": 50},
    {"section": "간호 및 건강관리", "sub": None, "title": "투약기록지", "order": 51},
    {"section": "간호 및 건강관리", "sub": None, "title": "간호기록지", "order": 52},
    {"section": "간호 및 건강관리", "sub": None, "title": "활력징후 기록", "order": 53},
    {"section": "간호 및 건강관리", "sub": None, "title": "욕창 위험도 평가", "order": 54},
    {"section": "간호 및 건강관리", "sub": None, "title": "욕창 관리기록", "order": 55},
    {"section": "간호 및 건강관리", "sub": None, "title": "낙상 위험도 평가", "order": 56},
    {"section": "간호 및 건강관리", "sub": None, "title": "낙상 관리기록", "order": 57},
    {"section": "간호 및 건강관리", "sub": None, "title": "감염관리 기록", "order": 58},
    {"section": "간호 및 건강관리", "sub": None, "title": "응급상황 기록", "order": 59},
    {"section": "간호 및 건강관리", "sub": None, "title": "사고보고서", "order": 60},
    {"section": "간호 및 건강관리", "sub": None, "title": "병원 진료기록", "order": 61},
    {"section": "간호 및 건강관리", "sub": None, "title": "촉탁의 진료기록", "order": 62},
    {"section": "간호 및 건강관리", "sub": None, "title": "신체억제 사용기록(해당 시)", "order": 63},
    {"section": "간호 및 건강관리", "sub": None, "title": "응급약품 관리", "order": 64},
    {"section": "프로그램 운영", "sub": None, "title": "연간 프로그램 계획", "order": 65},
    {"section": "프로그램 운영", "sub": None, "title": "월간 프로그램 계획", "order": 66},
    {"section": "프로그램 운영", "sub": None, "title": "프로그램 운영일지", "order": 67},
    {"section": "프로그램 운영", "sub": None, "title": "프로그램 참여자 명단", "order": 68},
    {"section": "프로그램 운영", "sub": None, "title": "프로그램 사진", "order": 69},
    {"section": "프로그램 운영", "sub": None, "title": "프로그램 평가", "order": 70},
    {"section": "프로그램 운영", "sub": None, "title": "치매 프로그램 운영자료", "order": 71},
    {"section": "프로그램 운영", "sub": None, "title": "여가 프로그램 운영자료", "order": 72},
    {"section": "사례관리 및 회의", "sub": None, "title": "사례회의록", "order": 73},
    {"section": "사례관리 및 회의", "sub": None, "title": "직원회의록", "order": 74},
    {"section": "사례관리 및 회의", "sub": None, "title": "보호자 상담기록", "order": 75},
    {"section": "사례관리 및 회의", "sub": None, "title": "욕구사정 기록", "order": 76},
    {"section": "사례관리 및 회의", "sub": None, "title": "고충처리 기록", "order": 77},
    {"section": "사례관리 및 회의", "sub": None, "title": "민원처리대장", "order": 78},
    {"section": "급여청구 및 회계", "sub": "급여청구", "title": "급여비용 청구자료", "order": 79},
    {"section": "급여청구 및 회계", "sub": "급여청구", "title": "청구 근거자료", "order": 80},
    {"section": "급여청구 및 회계", "sub": "급여청구", "title": "청구 수정자료", "order": 81},
    {"section": "급여청구 및 회계", "sub": "본인부담금", "title": "본인부담금 수납대장", "order": 82},
    {"section": "급여청구 및 회계", "sub": "본인부담금", "title": "영수증", "order": 83},
    {"section": "급여청구 및 회계", "sub": "본인부담금", "title": "미수금 관리", "order": 84},
    {"section": "급여청구 및 회계", "sub": "회계", "title": "회계장부", "order": 85},
    {"section": "급여청구 및 회계", "sub": "회계", "title": "지출결의서", "order": 86},
    {"section": "급여청구 및 회계", "sub": "회계", "title": "세금계산서", "order": 87},
    {"section": "급여청구 및 회계", "sub": "회계", "title": "거래명세서", "order": 88},
    {"section": "급여청구 및 회계", "sub": "회계", "title": "통장거래내역", "order": 89},
    {"section": "시설 및 안전관리", "sub": "소방", "title": "소방훈련 실시기록", "order": 90},
    {"section": "시설 및 안전관리", "sub": "소방", "title": "소방점검 결과", "order": 91},
    {"section": "시설 및 안전관리", "sub": "소방", "title": "소화기 관리", "order": 92},
    {"section": "시설 및 안전관리", "sub": "소방", "title": "피난유도등 점검", "order": 93},
    {"section": "시설 및 안전관리", "sub": "소방", "title": "비상벨 점검", "order": 94},
    {"section": "시설 및 안전관리", "sub": "시설", "title": "시설안전점검표", "order": 95},
    {"section": "시설 및 안전관리", "sub": "시설", "title": "전기 안전점검", "order": 96},
    {"section": "시설 및 안전관리", "sub": "시설", "title": "가스 안전점검", "order": 97},
    {"section": "시설 및 안전관리", "sub": "시설", "title": "승강기 점검", "order": 98},
    {"section": "시설 및 안전관리", "sub": "시설", "title": "보일러 점검", "order": 99},
    {"section": "시설 및 안전관리", "sub": "시설", "title": "비상발전기 점검(해당 시)", "order": 100},
    {"section": "시설 및 안전관리", "sub": "위생", "title": "환경위생 관리", "order": 101},
    {"section": "시설 및 안전관리", "sub": "위생", "title": "소독기록", "order": 102},
    {"section": "시설 및 안전관리", "sub": "위생", "title": "세탁관리", "order": 103},
    {"section": "시설 및 안전관리", "sub": "위생", "title": "쓰레기 관리", "order": 104},
    {"section": "시설 및 안전관리", "sub": "위생", "title": "감염병 관리대장", "order": 105},
    {"section": "급식관리", "sub": None, "title": "식단표", "order": 106},
    {"section": "급식관리", "sub": None, "title": "검식일지", "order": 107},
    {"section": "급식관리", "sub": None, "title": "보존식 관리", "order": 108},
    {"section": "급식관리", "sub": None, "title": "식재료 검수", "order": 109},
    {"section": "급식관리", "sub": None, "title": "위생점검표", "order": 110},
    {"section": "급식관리", "sub": None, "title": "조리종사자 건강관리", "order": 111},
    {"section": "개인정보 및 정보보호", "sub": None, "title": "개인정보 동의서", "order": 112},
    {"section": "개인정보 및 정보보호", "sub": None, "title": "개인정보 관리대장", "order": 113},
    {"section": "개인정보 및 정보보호", "sub": None, "title": "개인정보 파기기록", "order": 114},
    {"section": "개인정보 및 정보보호", "sub": None, "title": "CCTV 관리대장", "order": 115},
    {"section": "개인정보 및 정보보호", "sub": None, "title": "영상정보 관리기록", "order": 116},
    {"section": "개인정보 및 정보보호", "sub": None, "title": "CCTV 안내문", "order": 117},
    {"section": "기타 운영관리", "sub": None, "title": "자원봉사 관리", "order": 118},
    {"section": "기타 운영관리", "sub": None, "title": "실습생 관리", "order": 119},
    {"section": "기타 운영관리", "sub": None, "title": "후원금 관리(해당 시)", "order": 120},
    {"section": "기타 운영관리", "sub": None, "title": "후원물품 관리", "order": 121},
    {"section": "기타 운영관리", "sub": None, "title": "지역사회 연계사업", "order": 122},
    {"section": "기타 운영관리", "sub": None, "title": "협약서(MOU)", "order": 123},
    {"section": "지도점검 전 최종 확인", "sub": "① 서류 일치 여부", "title": "근무표 ↔ 출퇴근기록 일치", "order": 124},
    {"section": "지도점검 전 최종 확인", "sub": "① 서류 일치 여부", "title": "급여기록 ↔ 청구자료 일치", "order": 125},
    {"section": "지도점검 전 최종 확인", "sub": "① 서류 일치 여부", "title": "간호기록 ↔ 투약기록 일치", "order": 126},
    {"section": "지도점검 전 최종 확인", "sub": "① 서류 일치 여부", "title": "프로그램 사진 ↔ 운영일지 일치", "order": 127},
    {"section": "지도점검 전 최종 확인", "sub": "① 서류 일치 여부", "title": "사례회의 ↔ 급여제공계획 반영 여부", "order": 128},
    {"section": "지도점검 전 최종 확인", "sub": "① 서류 일치 여부", "title": "입·퇴소 기록 ↔ 청구자료 일치", "order": 129},
    {"section": "지도점검 전 최종 확인", "sub": "② 서명 확인", "title": "수급자 서명", "order": 130},
    {"section": "지도점검 전 최종 확인", "sub": "② 서명 확인", "title": "보호자 서명", "order": 131},
    {"section": "지도점검 전 최종 확인", "sub": "② 서명 확인", "title": "담당자 서명", "order": 132},
    {"section": "지도점검 전 최종 확인", "sub": "② 서명 확인", "title": "결재 누락 여부", "order": 133},
    {"section": "지도점검 전 최종 확인", "sub": "③ 종사자 확인", "title": "자격증 유효 여부", "order": 134},
    {"section": "지도점검 전 최종 확인", "sub": "③ 종사자 확인", "title": "보수교육 완료 여부", "order": 135},
    {"section": "지도점검 전 최종 확인", "sub": "③ 종사자 확인", "title": "법정의무교육 완료 여부", "order": 136},
    {"section": "지도점검 전 최종 확인", "sub": "③ 종사자 확인", "title": "인력배치기준 충족 여부", "order": 137},
    {"section": "지도점검 전 최종 확인", "sub": "④ 시설 점검", "title": "비상약품 유효기간", "order": 138},
    {"section": "지도점검 전 최종 확인", "sub": "④ 시설 점검", "title": "소화기 유효기간", "order": 139},
    {"section": "지도점검 전 최종 확인", "sub": "④ 시설 점검", "title": "피난유도등 작동", "order": 140},
    {"section": "지도점검 전 최종 확인", "sub": "④ 시설 점검", "title": "비상벨 작동", "order": 141},
    {"section": "지도점검 전 최종 확인", "sub": "④ 시설 점검", "title": "승강기 정상 작동", "order": 142},
    {"section": "지도점검 전 최종 확인", "sub": "④ 시설 점검", "title": "CCTV 정상 작동", "order": 143},
    {"section": "지도점검 전 최종 확인", "sub": "⑤ 현장 확인", "title": "게시판 공지 최신화", "order": 144},
    {"section": "지도점검 전 최종 확인", "sub": "⑤ 현장 확인", "title": "비상연락망 게시", "order": 145},
    {"section": "지도점검 전 최종 확인", "sub": "⑤ 현장 확인", "title": "기관 현황 게시", "order": 146},
    {"section": "지도점검 전 최종 확인", "sub": "⑤ 현장 확인", "title": "직원 명찰 착용", "order": 147},
    {"section": "지도점검 전 최종 확인", "sub": "⑤ 현장 확인", "title": "환경정리 상태", "order": 148},
    {"section": "지도점검 전 최종 확인", "sub": "⑤ 현장 확인", "title": "서류철 정리", "order": 149},
    {"section": "지도점검 전 최종 확인", "sub": "⑤ 현장 확인", "title": "전산기록 확인", "order": 150},
    {"section": "지도점검 전 최종 확인", "sub": "⑤ 현장 확인", "title": "최근 변경사항 반영 완료", "order": 151},
]
