"""Add guardians photos message_logs tables

Revision ID: 4c904d2a22ee
Revises: 3d6a6c33175b
Create Date: 2026-04-20 20:54:15.774472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c904d2a22ee'
down_revision: Union[str, None] = '3d6a6c33175b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardians',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resident_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('receive_kakao', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_phone'), 'guardians', ['phone'], unique=False)
    op.create_index(op.f('ix_guardians_resident_id'), 'guardians', ['resident_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resident_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_resident_id'), 'photos', ['resident_id'], unique=False)
    op.create_table('message_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('resident_id', sa.String(), nullable=False),
    sa.Column('guardian_id', sa.String(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('photo_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['residents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_logs_guardian_id'), 'message_logs', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_message_logs_resident_id'), 'message_logs', ['resident_id'], unique=False)
    op.create_index(op.f('ix_message_logs_sent_at'), 'message_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_message_logs_status'), 'message_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_logs_status'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_sent_at'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_resident_id'), table_name='message_logs')
    op.drop_index(op.f('ix_message_logs_guardian_id'), table_name='message_logs')
    op.drop_table('message_logs')
    op.drop_index(op.f('ix_photos_resident_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_guardians_resident_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_phone'), table_name='guardians')
    op.drop_table('guardians')
    # ### end Alembic commands ###
