"""add family stories tables

Revision ID: 6c7fe654c159
Revises: 4c904d2a22ee
Create Date: 2026-04-29 13:49:39.157773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '6c7fe654c159'
down_revision: Union[str, None] = '4c904d2a22ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'family_stories',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, 
                  server_default=sa.text('gen_random_uuid()')),
        sa.Column('resident_id', UUID(as_uuid=True), nullable=False),
        sa.Column('author_id', UUID(as_uuid=True), nullable=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('content', sa.Text, nullable=False),
        sa.Column('story_date', sa.Date, nullable=False),
        sa.Column('status', sa.String(20), nullable=False, server_default='draft'),
        sa.Column('privacy_confirmed', sa.Boolean, nullable=False, 
                  server_default='false'),
        sa.Column('created_at', sa.DateTime, nullable=False, 
                  server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime, nullable=False, 
                  server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.CheckConstraint("status IN ('draft', 'published')", 
                          name='check_story_status')
    )
    
    op.create_index('idx_family_stories_resident', 'family_stories', ['resident_id'])
    op.create_index('idx_family_stories_status', 'family_stories', ['status'])
    op.create_index('idx_family_stories_date', 'family_stories', 
                    [sa.text('story_date DESC')])
    
    # ===== 2. family_story_photos 테이블 =====
    op.create_table(
        'family_story_photos',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, 
                  server_default=sa.text('gen_random_uuid()')),
        sa.Column('story_id', UUID(as_uuid=True), nullable=False),
        sa.Column('file_url', sa.String(500), nullable=False),
        sa.Column('file_name', sa.String(255), nullable=False),
        sa.Column('display_order', sa.Integer, nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime, nullable=False, 
                  server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['story_id'], ['family_stories.id'], 
                               ondelete='CASCADE'),
    )
    
    op.create_index('idx_family_story_photos_story', 'family_story_photos', 
                    ['story_id'])
    op.create_index('idx_family_story_photos_order', 'family_story_photos', 
                    ['story_id', 'display_order'])
    
    # ===== 3. guardians 테이블 컬럼 추가 =====
    # 주의: 기존 guardians 테이블이 있는 경우에만 실행
    # 없으면 이 부분 주석 처리 또는 삭제
    try:
        op.add_column('guardians', 
                      sa.Column('password_hash', sa.String(255), nullable=True))
        op.add_column('guardians', 
                      sa.Column('last_login_at', sa.DateTime, nullable=True))
        op.add_column('guardians', 
                      sa.Column('is_active', sa.Boolean, server_default='true'))
        op.create_index('idx_guardians_phone', 'guardians', ['phone'], unique=True)
    except Exception as e:
        print(f"Guardians columns already exist or table not found: {e}")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_story_photos')
    op.drop_table('family_stories')
    
