"""add click_events table

Revision ID: 9708749016a9
Revises: dd5268ecd651
Create Date: 2026-03-15 09:24:30.073813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9708749016a9'
down_revision: Union[str, None] = 'dd5268ecd651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ip_hash', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_created_at'), 'click_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_click_events_ip_hash'), 'click_events', ['ip_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_events_ip_hash'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_created_at'), table_name='click_events')
    op.drop_table('click_events')
    # ### end Alembic commands ###
